using System.Text;
using System.Text.RegularExpressions;

namespace SupportForge.Ingestion.Code;

// Tier 0 of the code-graph classification pipeline (docs/plans/2026-08-16-001-feat-code-graph-
// classification-plan.md, U2): a language-independent gate on file *shape*, not syntax, so every
// check here works identically regardless of programming language. Nothing here excludes a file
// from the graph on its own except the binary/encoding/empty checks -- Minified/Generated/Banner
// are marks consumed by later pipeline stages (Tier 2 enrichment, the classification policy), never
// a standalone exclusion decision. Path/directory name is deliberately not a signal here at all.
[Flags]
public enum CodeFileShape
{
    None = 0,
    Minified = 1,
    Generated = 2,
    Banner = 4,
    Oversized = 8,
}

public readonly record struct CodeFileAdmissibilityResult(bool IsAdmissible, CodeFileShape Shape);

public static class CodeFileAdmissibility
{
    private const int BinaryScanBytes = 8192;
    private const int OversizedBytes = 1024 * 1024;
    private const int BannerScanLines = 5;
    private const int GeneratedScanLines = 20;
    private const int MinifiedMaxLineLength = 1000;
    private const double MinifiedMeanLineLength = 200;
    private const double MinifiedMinCharsPerNewline = 500;

    private static readonly string[] GeneratedContentMarkers =
        ["<auto-generated", "DO NOT EDIT", "@generated", "Code generated by"];

    private static readonly string[] GeneratedFileNameMarkers =
        [".g.", ".designer.", ".generated.", "_pb2", ".pb.go"];

    private static readonly Regex CopyrightPattern = new(
        @"Copyright\s*\(c\)\s*\d{4}", RegexOptions.IgnoreCase | RegexOptions.Compiled);

    private static readonly Regex VersionStringPattern = new(
        @"\bv?\d+\.\d+(\.\d+)?\b", RegexOptions.Compiled);

    public static CodeFileAdmissibilityResult Classify(string fileName, byte[] content)
    {
        if (content.Length == 0) return new(false, CodeFileShape.None);

        var scanLen = Math.Min(content.Length, BinaryScanBytes);
        for (var i = 0; i < scanLen; i++)
            if (content[i] == 0) return new(false, CodeFileShape.None);

        var text = DecodeText(content);
        if (text is null || string.IsNullOrWhiteSpace(text)) return new(false, CodeFileShape.None);

        var shape = CodeFileShape.None;
        if (content.Length > OversizedBytes) shape |= CodeFileShape.Oversized;

        var lines = text.Split('\n');
        if (IsMinifiedShape(text, lines)) shape |= CodeFileShape.Minified;
        if (IsGeneratedShape(fileName, lines)) shape |= CodeFileShape.Generated;
        if (IsBannerShape(lines)) shape |= CodeFileShape.Banner;

        return new(true, shape);
    }

    // Strict UTF-8 first (the common case), then BOM-marked UTF-16; anything else is treated as
    // undecodable rather than silently mangled via a lossy fallback encoding.
    private static string? DecodeText(byte[] content)
    {
        if (content.Length >= 2 && content[0] == 0xFF && content[1] == 0xFE)
            return Encoding.Unicode.GetString(content, 2, content.Length - 2);
        if (content.Length >= 2 && content[0] == 0xFE && content[1] == 0xFF)
            return Encoding.BigEndianUnicode.GetString(content, 2, content.Length - 2);

        try
        {
            var strictUtf8 = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false, throwOnInvalidBytes: true);
            return strictUtf8.GetString(content);
        }
        catch (DecoderFallbackException)
        {
            return null;
        }
    }

    private static bool IsMinifiedShape(string text, string[] lines)
    {
        var longestLine = lines.Max(l => l.TrimEnd('\r').Length);
        var meanLineLength = lines.Length > 0 ? (double)text.Length / lines.Length : 0;
        var newlineCount = lines.Length - 1;
        var charsPerNewline = newlineCount > 0 ? (double)text.Length / newlineCount : text.Length;

        if (longestLine > MinifiedMaxLineLength) return true;
        if (meanLineLength > MinifiedMeanLineLength) return true;
        if (charsPerNewline > MinifiedMinCharsPerNewline) return true;

        return lines.Any(l => l.TrimStart().StartsWith("//# sourceMappingURL=", StringComparison.Ordinal));
    }

    private static bool IsGeneratedShape(string fileName, string[] lines)
    {
        var head = string.Join('\n', lines.Take(GeneratedScanLines));
        if (GeneratedContentMarkers.Any(m => head.Contains(m, StringComparison.OrdinalIgnoreCase)))
            return true;

        return GeneratedFileNameMarkers.Any(m => fileName.Contains(m, StringComparison.OrdinalIgnoreCase));
    }

    private static bool IsBannerShape(string[] lines)
    {
        var head = string.Join('\n', lines.Take(BannerScanLines));
        if (head.Contains("@license", StringComparison.OrdinalIgnoreCase)) return true;
        if (head.Contains("@preserve", StringComparison.OrdinalIgnoreCase)) return true;
        // Copyright notice plus a version string somewhere in the same window -- not necessarily
        // adjacent (e.g. "moment.js v2.29.4 | Copyright (c) 2024 Moment.js contributors").
        return CopyrightPattern.IsMatch(head) && VersionStringPattern.IsMatch(head);
    }
}
