using System.Text;
using SupportForge.Ingestion.Code;
using Xunit;

namespace SupportForge.Api.Tests.Ingestion;

public class CodeFileAdmissibilityTests
{
    private static byte[] Bytes(string text) => Encoding.UTF8.GetBytes(text);

    [Fact]
    public void Classify_RejectsBinaryContent_NulByteInFirst8KB()
    {
        var content = new byte[] { 0x50, 0x4B, 0x00, 0x03, 0x04 };
        var result = CodeFileAdmissibility.Classify("archive.zip", content);
        Assert.False(result.IsAdmissible);
    }

    [Fact]
    public void Classify_RejectsInvalidUtf8Content()
    {
        // 0xFF 0xFE without being a valid UTF-16 BOM pairing, followed by an invalid continuation
        // byte sequence that neither strict UTF-8 nor the BOM-detection path can decode.
        var content = new byte[] { 0xC3, 0x28, 0xA0, 0xA1 };
        var result = CodeFileAdmissibility.Classify("weird.dat", content);
        Assert.False(result.IsAdmissible);
    }

    [Fact]
    public void Classify_RejectsWhitespaceOnlyContent()
    {
        var result = CodeFileAdmissibility.Classify("blank.txt", Bytes("   \n\t\n   \n"));
        Assert.False(result.IsAdmissible);
    }

    [Fact]
    public void Classify_RejectsEmptyContent()
    {
        var result = CodeFileAdmissibility.Classify("empty.txt", []);
        Assert.False(result.IsAdmissible);
    }

    [Fact]
    public void Classify_AdmitsOversizedFile_WithOversizedFlag()
    {
        var content = Bytes(new string('a', 1024 * 1024 + 10));
        var result = CodeFileAdmissibility.Classify("big.txt", content);
        Assert.True(result.IsAdmissible);
        Assert.True(result.Shape.HasFlag(CodeFileShape.Oversized));
    }

    [Fact]
    public void Classify_MarksMinified_WhenOneLineExceedsLengthThreshold()
    {
        var content = Bytes(new string('x', 1500));
        var result = CodeFileAdmissibility.Classify("bundle.js", content);
        Assert.True(result.IsAdmissible);
        Assert.True(result.Shape.HasFlag(CodeFileShape.Minified));
    }

    [Fact]
    public void Classify_MarksMinified_WhenSourceMapTrailerPresent()
    {
        var content = Bytes("function a(){}\nfunction b(){}\n//# sourceMappingURL=app.js.map\n");
        var result = CodeFileAdmissibility.Classify("app.js", content);
        Assert.True(result.IsAdmissible);
        Assert.True(result.Shape.HasFlag(CodeFileShape.Minified));
    }

    [Fact]
    public void Classify_MarksGenerated_WhenAutoGeneratedHeaderPresent()
    {
        var content = Bytes("// <auto-generated />\nnamespace Demo;\npublic class Foo {}\n");
        var result = CodeFileAdmissibility.Classify("Foo.cs", content);
        Assert.True(result.IsAdmissible);
        Assert.True(result.Shape.HasFlag(CodeFileShape.Generated));
    }

    [Fact]
    public void Classify_MarksGenerated_WhenFileNameMatchesGeneratedPattern()
    {
        var content = Bytes("public partial class Model {}\n");
        var result = CodeFileAdmissibility.Classify("Model.designer.cs", content);
        Assert.True(result.IsAdmissible);
        Assert.True(result.Shape.HasFlag(CodeFileShape.Generated));
    }

    [Fact]
    public void Classify_MarksBanner_WhenCopyrightWithVersionInFirstFiveLines()
    {
        var content = Bytes("/*!\n * jQuery Foundation, Copyright (c) 2024 jQuery. v3.7.1\n */\nfunction a(){}\n");
        var result = CodeFileAdmissibility.Classify("jquery.js", content);
        Assert.True(result.IsAdmissible);
        Assert.True(result.Shape.HasFlag(CodeFileShape.Banner));
    }

    [Fact]
    public void Classify_MarksBanner_WhenLicenseKeywordPresent()
    {
        var content = Bytes("/*! @license MIT */\nfunction a(){}\n");
        var result = CodeFileAdmissibility.Classify("lib.js", content);
        Assert.True(result.IsAdmissible);
        Assert.True(result.Shape.HasFlag(CodeFileShape.Banner));
    }

    [Fact]
    public void Classify_AdmitsNormalHandwrittenFile_WithNoShapeMarks()
    {
        var content = Bytes("namespace Demo;\n\npublic sealed class Auth\n{\n    public void Login() { }\n}\n");
        var result = CodeFileAdmissibility.Classify("Auth.cs", content);
        Assert.True(result.IsAdmissible);
        Assert.Equal(CodeFileShape.None, result.Shape);
    }

    // The actual shape of the incident's polluting files: minified content carrying a license banner.
    [Fact]
    public void Classify_MarksBothMinifiedAndBanner_ForVendoredLibraryShape()
    {
        var content = Bytes(
            "/*! moment.js v2.29.4 | Copyright (c) 2024 Moment.js contributors */\n" +
            new string('a', 1200) + "\n");
        var result = CodeFileAdmissibility.Classify("moment.js", content);
        Assert.True(result.IsAdmissible);
        Assert.True(result.Shape.HasFlag(CodeFileShape.Minified));
        Assert.True(result.Shape.HasFlag(CodeFileShape.Banner));
    }
}
